version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: court_booking_db
    restart: always
    environment:
      POSTGRES_DB: court_booking
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
